planner_name: velocity_reversal_lipm
swing_height: 0.1
push_down_height: 0.0
#push_down_height: 0.02
default_target_foot_location: [-0.07, 0.13, 0.0]

## Feedback Gain
# virtual (x, y, z, Rx, Ry, Rz) config x6
# Kp: [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
# Kd: [ 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0]

Kp: [ 0, 0, 0, 0, 0, 0, 300, 300, 400, 300, 350, 250]
Kd: [ 0, 0, 0, 0, 0, 0, 15,  10,  10,  15,  15,  10]

# stance(right) & swing (left)
# Kp: [ 0, 0, 0, 0, 0, 0, 50, 50, 50, 10, 10, 10]
# Kd: [ 0, 0, 0, 0, 0, 0, 5,  5,  5,  2,  2,  2]

gain_decreasing_ratio: 1.0
gain_decreasing_period_portion: 0.0

body_pt_offset: [0.0, 0.0]
swing_time_reduction: 0.0
foot_landing_offset: [-0.0, 0.]

#body_pt_offset: [-0.077, 0.0]
#foot_landing_offset: [0.0, 0.]
#swing_time_reduction: 0.0

initial_planning: false
#initial_planning: true
kp_x: 1.0
kp_y: 0.5

hip_knee_retraction_angle: [-0.639, 1.17]

